######### Basic Settings #########
basic:
    prefix: reproduce
    device: '1'
    seed: [0] 
    num_workers: 8

    # Dataset Choises: ultrasound_dataset
    dataset: ultrasound_dataset

    # Method Choises: 
    method: finetune

    # Backbone Choises: resnet18, resnet18_cbam, resnet50, resnet101
    backbone: resnet101
    pretrained: true
    # pretrain_path: pretrain_models/imagenet200_resnet18_cbam_pretrained.pth
    freeze: false
    save_models: true # if true, programm will save model's weights during incremental train

    save_name: res101_5fold_all

options:
    ultrasound_dataset:
        split_for_valid: true # if kfold>1, it will be ignored
        
        kfold: 5
        epochs: 2
        batch_size: 16

        lrate: 0.0001
        opt_type: adam

        scheduler: multi_step # cos
        milestones: [40, 80, 120]
        lrate_decay: 0.1 

        criterion: ce

        # select_list: [0, 1, 8]
        # select_list: [0, 1, 2, 3, 8]
        select_list: [0, 1, 2, 3, 4, 5, 6, 7, 8]