######### Basic Settings #########
basic:
    device: '1'
    seed: [0] 
    num_workers: 8

    # Dataset Choises: ultrasound_dataset
    dataset: ultrasound_dataset2
    split_for_valid: true # if kfold>1, it will be ignored
    kfold: 1

    # Method Choises: 
    method: finetune

    backbone: multi_branch_sum
    base_backbone: resnet18
    pretrained: true
    # pretrain_path: pretrain_models/imagenet200_resnet18_cbam_pretrained.pth
    freeze: false
    select_list: [0, 1, 2, 3, 4, 5, 6, 7, 8]

    save_models: true # if true, programm will save model's weights during incremental train

    get_roc_auc: true
    
    save_name: multi_branch_sum_all_dataset2

options:
    ultrasound_dataset1:
        
        epochs: 150 # 150
        batch_size: 16

        lrate: 0.0001
        opt_type: adam

        scheduler: multi_step # cos
        # milestones: [40, 80, 120]
        milestones: [40, 80, 120, 160]
        lrate_decay: 0.1 

        criterion: ce

    ultrasound_dataset2:
        
        epochs: 150 # 150
        batch_size: 16

        lrate: 0.0001
        opt_type: adam

        scheduler: multi_step # cos
        # milestones: [40, 80, 120]
        milestones: [40, 80, 120, 160]
        lrate_decay: 0.1 

        criterion: ce      

    ultrasound_dataset1_224:
        
        epochs: 150 # 150
        batch_size: 16

        lrate: 0.0001
        opt_type: adam

        scheduler: multi_step # cos
        # milestones: [40, 80, 120]
        milestones: [40, 80, 120, 160]
        lrate_decay: 0.1 

        criterion: ce

    ultrasound_dataset2_224:
        
        epochs: 150 # 150
        batch_size: 16

        lrate: 0.0001
        opt_type: adam

        scheduler: multi_step # cos
        # milestones: [40, 80, 120]
        milestones: [40, 80, 120, 160]
        lrate_decay: 0.1 

        criterion: ce