######### Basic Settings #########
basic:
    device: '0'
    # seed: [0] 
    num_workers: 8

    # Dataset Choises: ultrasound_dataset
    dataset: ultrasound_dataset1
    split_for_valid: true # if kfold>1, it will be ignored
    kfold: 1

    # Method Choises: 
    method: retrain

    pretrained: true
    pretrain_path: logs/mocoV2/mocoV_resnet50_all_dataset1_2022-08-01-12-11-17/model_dict_101.pkl
    freeze: true

    save_models: true # if true, programm will save model's weights during incremental train

    get_roc_auc: true


options:
    ultrasound_dataset1:
        
        epochs: 150 # 150
        batch_size: 16

        lrate: 0.0001
        opt_type: adam

        scheduler: multi_step # cos
        # milestones: [40, 80, 120]
        milestones: [40, 80, 120, 160]
        lrate_decay: 0.1 

        criterion: ce

    ultrasound_dataset2:
        
        epochs: 150 # 150
        batch_size: 16

        lrate: 0.0001
        opt_type: adam

        scheduler: multi_step # cos
        # milestones: [40, 80, 120]
        milestones: [40, 80, 120, 160]
        lrate_decay: 0.1 

        criterion: ce      

    ultrasound_dataset1_224:
        
        epochs: 150 # 150
        batch_size: 16

        lrate: 0.0001
        opt_type: adam

        scheduler: multi_step # cos
        # milestones: [40, 80, 120]
        milestones: [40, 80, 120, 160]
        lrate_decay: 0.1 

        criterion: ce

    ultrasound_dataset2_224:
        
        epochs: 150 # 150
        batch_size: 16

        lrate: 0.0001
        opt_type: adam

        scheduler: multi_step # cos
        # milestones: [40, 80, 120]
        milestones: [40, 80, 120, 160]
        lrate_decay: 0.1 

        criterion: ce        