######### Basic Settings #########
basic:
    prefix: reproduce
    device: '0'
    seed: [0] 
    num_workers: 8

    dataset: ultrasound_dataset2
    # split_for_valid: False (default)

    # Method Choises: 
    method: test

    pretrain_path: logs/finetune/resnet18_test/trainer0_model_dict.pkl
    
    batch_size: 16
    # save_name: test_multi_branch_cat_018
    
            
