######### Basic Settings #########
basic:
    prefix: reproduce
    device: '0'
    seed: [0] 
    num_workers: 8

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: ultrasound_dataset

    ret_valid: true

    # Method Choises: 
    method: test

    pretrained: true
    pretrain_path: logs/finetune/multi_branch_sum_018_test/trainer0_model_dict_2.pkl
    
    batch_size: 16

    img_size: 100
    save_name: test_multi_branch_cat_018
    
            
