######### Basic Settings #########
basic:
    device: '1'
    seed: [0] 
    num_workers: 8

    # dataset: ultrasound_dataset2
    # split_for_valid: False (default)

    # Method Choises: 
    method: test

    pretrain_path: logs/finetune/resnet101_all_dataset1_test_2022-08-04-06-35-55/trainer0_model_dict_1.pkl

    get_roc_auc: true

    get_mistake: true
    
    batch_size: 16
    # save_name: test_multi_branch_cat_018
    
            
